apiVersion: v1
kind: Service
metadata:
  name: apm-eureka
spec:
  selector:
    app: apm-eureka
  ports:
    - port: 8761
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: apm-item
spec:
  selector:
    app: apm-item
  ports:
    - port: 8082
  type: NodePort
