server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false

#spring:
#  security:
#    user:
#      name: xuhe
#      password: 123456